auth_app/urls.py
"""Urls for auth_app."""
from django.contrib.auth.views import LogoutView
from django.urls import path

from auth_app.views import CustomLoginView, CustomPasswordChangeView, RegisterView

app_name = "auth"

urlpatterns = [
    path("sign-up/", RegisterView.as_view(), name="sign_up"),
    path("sign-in/", CustomLoginView.as_view(), name="sign_in"),
    path(
        "password-change/",
        CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("logout/", LogoutView.as_view(next_page="vpn:index"), name="logout"),
]

config/urls.py
"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/

Examples.
    - function views
        1. Add an import:  from my_app import views
        2. Add a URL to urlpatterns:  path('', views.home, name='home')
    - class-based views
        1. Add an import:  from other_app.views import Home
        2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
    - including another URLconf
        1. Import the include() function: from django.urls import include, path
        2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("auth_app.urls")),
    path("", include("vpn_app.urls")),
]

vpn_app/urls.py
"""Urls for vpn_app."""
from django.urls import path, re_path

from vpn_app.views import (
    AccountView,
    CreateSiteLinkView,
    DeleteSiteLinkView,
    IndexView,
    UpdateSiteLinkView,
    VpnProxyView,
)

app_name = "vpn"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("create-site-link/", CreateSiteLinkView.as_view(), name="create_site_link"),
    path(
        "update-site-link/<int:owner_id>/<str:slug>/",
        UpdateSiteLinkView.as_view(),
        name="update_site_link",
    ),
    path(
        "delete-site-link/<int:owner_id>/<str:slug>/",
        DeleteSiteLinkView.as_view(),
        name="delete_site_link",
    ),
    path("account/<int:pk>/", AccountView.as_view(), name="account"),
    re_path(
        r"^localhost/(?P<path>([^/]+/?)*)$",  # noqa WPS360
        VpnProxyView.as_view(),
        name="vpn_local_view",
    ),
    re_path(r"(?P<path>.*)", VpnProxyView.as_view(), name="vpn_view"),  # noqa WPS360
]

vpn_app/models.py
"""Models for vpn_app."""
from django.contrib.auth.models import User
from django.db import models

from vpn_app.validators import validate_domain


class VpnSite(models.Model):
    """Model for site data."""

    schemes = [("http", "http"), ("https", "https")]

    name = models.CharField(max_length=100, verbose_name="Site name")
    domain = models.CharField(
        max_length=200,
        validators=[validate_domain],
        verbose_name="Site domain",
    )
    scheme = models.CharField(
        max_length=20,
        choices=schemes,
        default="http",
        verbose_name="Scheme",
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Site owner")
    used_links_number = models.BigIntegerField(
        default=0,
        verbose_name="Used links number",
    )
    sended_volume = models.BigIntegerField(default=0, verbose_name="Sended data volume")
    loaded_volume = models.BigIntegerField(default=0, verbose_name="Loaded data volume")

    def __str__(self) -> str:
        """Represent model."""
        return str(self.name)

vpn_app/forms.py
"""Forms for vpn_app."""
import typing

from django import forms
from django.contrib.auth.models import User

from vpn_app.models import VpnSite


class UserAccountForm(forms.ModelForm):
    """Form for User model."""

    class Meta:  # noqa WPS306
        """Class Meta for UserAccountForm."""

        model = User
        fields = ("username", "email", "first_name", "last_name")

    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        """Rewrite fields class."""
        super().__init__(*args, **kwargs)
        fields = self.fields
        fields["username"].widget.attrs["class"] = "custom-input custom-input-height"
        fields["email"].widget.attrs["class"] = "custom-input custom-input-height"
        fields["first_name"].widget.attrs["class"] = "custom-input custom-input-height"
        fields["last_name"].widget.attrs["class"] = "custom-input custom-input-height"


class VpnSiteCreateForm(forms.ModelForm):
    """Form for PersonalSite model instance creation."""

    def __init__(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        """Rewrite fields styling."""
        super().__init__(*args, **kwargs)
        fields = self.fields
        fields["name"].widget.attrs["class"] = "custom-input custom-input-height"
        fields["domain"].widget.attrs["class"] = "custom-input custom-input-height"
        fields["scheme"].widget.attrs["class"] = "custom-input custom-input-height"

    class Meta:  # noqa WPS306
        """Class Meta for PersonalSiteCreateForm."""

        model = VpnSite
        fields = ("name", "domain", "scheme")

vpn_app/views.py
"""Views for vpn_app."""
import typing

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import QuerySet
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic

from project_services import mixins
from vpn_app import forms
from vpn_app.app_views import BaseVpnProxyView
from vpn_app.models import VpnSite


class IndexView(generic.TemplateView):
    """Index view."""

    template_name = "vpn_app/index.html"
    extra_context = {"title": "Welcome"}


class CreateSiteLinkView(
    LoginRequiredMixin,
    mixins.ChangeSuccessURLMixin,
    generic.FormView,
):
    """Create site view."""

    form_class = forms.VpnSiteCreateForm
    template_name = "vpn_app/site/create_site_link.html"
    extra_context = {"title": "Create vpn link"}
    success_url = reverse_lazy("auth:sign_up")

    def form_valid(self, form: forms.VpnSiteCreateForm) -> HttpResponse:
        """Create personal site."""
        form_data: dict = form.cleaned_data
        if self.request.user.is_authenticated:
            VpnSite(**form_data, owner=self.request.user).save()
        return super().form_valid(form)


class UpdateSiteLinkView(
    mixins.CustomUserPassesTestMixin,
    mixins.ChangeSuccessURLMixin,
    generic.UpdateView,
):
    """Update site view."""

    form_class = forms.VpnSiteCreateForm
    template_name = "vpn_app/site/update_site_link.html"
    extra_context = {"title": "Update site link"}
    success_url = reverse_lazy("auth:sign_up")
    slug_field = "domain"

    def get_queryset(self) -> QuerySet:
        """Return queryset using current user."""
        if self.request.user.is_authenticated:
            return VpnSite.objects.filter(owner=self.request.user)
        return VpnSite.objects.filter(owner=None)


class DeleteSiteLinkView(  # type: ignore
    mixins.CustomUserPassesTestMixin,
    mixins.ChangeSuccessURLMixin,
    generic.DeleteView,
):
    """Delete PersonalSite model instance."""

    model = VpnSite
    template_name = "vpn_app/site/delete_site_link.html"
    extra_context = {"title": "Delete site link"}
    success_url = reverse_lazy("auth:sign_up")
    slug_field = "domain"

    def get_queryset(self) -> QuerySet:
        """Return queryset using current user."""
        if self.request.user.is_authenticated:
            return VpnSite.objects.filter(owner=self.request.user)
        return VpnSite.objects.filter(owner=None)


class AccountView(
    mixins.CustomUserPassesTestMixin,
    mixins.ChangeSuccessURLMixin,
    generic.UpdateView,
):
    """Update user information."""

    model = User
    form_class = forms.UserAccountForm
    template_name = "vpn_app/account.html"
    extra_context = {"title": "Personal info"}
    success_url = reverse_lazy("auth:sign_up")

    def get_context_data(self, **kwargs: typing.Any) -> dict:
        """Get context data."""
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            context["vpn_sites"] = VpnSite.objects.filter(owner=user)
        return context


class VpnProxyView(BaseVpnProxyView):
    """Proxy view."""

    retries = 2
    add_x_forwarded = True

vpn_app/templates/vpn_app/account.html
{% extends 'vpn_app/base.html' %}
{% load static %}
{% block content %}
    <div class="w-100 p-2 d-flex flex-column align-items-center">
        <div class="w-100 d-flex flex-column align-items-center">
            <div class="fs-2">{{ title }}</div>
            <form method="post" class="w-100 d-flex flex-column align-items-center" style="max-width: 400px">
                <div class="w-100">
                    {% csrf_token %}
                {% if form.error %}
                    <div>{{ form.error }}</div>
                {% endif %}
                {% for f in form %}
                    <div class="my-2">{{ f.label }}</div>
                    <div class="w-100">{{ f }}</div>
                    {% if f.errors %}
                        <div>{{ f.errors }}</div>
                    {% endif %}
                {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary mt-4">Submit changes</button>
            </form>
            <div class="w-100 d-flex flex-row">
                <a class="m-2" href="{% url 'auth:password_change' %}">
                    <button class="btn btn-warning">Change password</button>
                </a>
            </div>
        </div>
        <div class="w-100 d-flex flex-column align-items-center">
            <div class="fs-2 m-2">Sites and links</div>
                <div class="w-100">
                    <a href="{% url 'vpn:create_site_link' %}">
                        <button class="btn btn-warning">Create site vpn link</button>
                    </a>
                    <div class="w-100 text-center fs-4">Already created sites links</div>
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">N</th>
                                <th scope="col">Site name</th>
                                <th scope="col">Site scheme</th>
                                <th scope="col">Site domain</th>
                                <th scope="col">Transition</th>
                                <th scope="col">Sended</th>
                                <th scope="col">Loaded</th>
                                <th scope="col">Update</th>
                                <th scope="col">Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for vpn_site in vpn_sites %}
                                {% with forloop.counter as index %}
                                    <tr>
                                        <th scope="row">{{ index }}</th>
                                        <th><a href="/localhost/{{ vpn_site.domain }}/">{{ vpn_site.name }}</a></th>
                                        <th><a href="/localhost/{{ vpn_site.domain }}/">{{ vpn_site.scheme }}</a></th>
                                        <th><a href="/localhost/{{ vpn_site.domain }}/">{{ vpn_site.domain }}</a></th>
                                        <th>{{ vpn_site.used_links_number }}</th>
                                        <th>{{ vpn_site.sended_volume }}</th>
                                        <th>{{ vpn_site.loaded_volume }}</th>
                                        <th><a href="{% url 'vpn:update_site_link' user.id vpn_site.domain %}">Click</a></th>
                                        <th><a href="{% url 'vpn:delete_site_link' user.id vpn_site.domain %}">Click</a></th>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

vpn_app/templates/vpn_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
         <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{{ title }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </head>
    <body class="bg-light">
    <style>
        .custom-input {
            border: 0;
            box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.3);
            width: 100%;
        }
        .custom-input-height {
            height: 48px; border-radius:12px;
        }
    </style>
        {% include 'vpn_app/top_bar.html' %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

vpn_app/templates/vpn_app/index.html
{% extends 'vpn_app/base.html' %}
{% load static %}
{% block content %}
    <div class="w-100 d-flex flex-column align-items-center">
        <div class="fs-1 p-4 text-primary">Welcome to VPN service</div>
        <div class="w-75">
            <p>In VPN service you can create your own vpn service.</p>
            <p>To gain the ability to create vpn you should register.</p>
            <p>
                Created links you'll find in account page.
                There will be statistic info also.
            </p>
            <p>
                Created list linkable. Click on any and serve choosen site in
                vpn mode.
            </p>
        </div>
    </div>
{% endblock %}

vpn_app/templates/vpn_app/top_bar.html
{% load static %}

<div
        class="w-100 p-2 bg-white d-flex flex-row justify-content-around align-items-center"
        style="height: 70px"
>
    <a href="{% url 'vpn:index'%}" class="fs-3 fw-bold text-danger">VPN</a>
    {% if user.is_anonymous %}
        <div class="d-flex flex-row">
            <a class="m-2 text-danger" href="{% url 'auth:sign_up' %}">Sign up</a>
            <a class="m-2 text-danger" href="{% url 'auth:sign_in' %}">Sign in</a>
        </div>
    {% else %}
        <div class="d-flex flex-row aling-items-center">
            <form class="d-flex flex-row align-items-center" action="{% url 'auth:logout' %}" method="post">
                {% csrf_token %}
                <input
                        class="text-danger border border-0 bg-transparent"
                        type="submit"
                        value="Logout"
                        style="text-decoration: underline"
                >
            </form>
            <a class="m-2 text-danger" id="aa" href="{% url 'vpn:account' user.id %}">Account</a>
        </div>

    {% endif %}
</div>